###

POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "password"
}

###

POST http://localhost:3030/api/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@user.com",
  "password": "password"
}

###

GET http://localhost:3030/api/auth/
Content-Type: application/json