### LOGIN USER

POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "password"
}

### REGISTER USER

POST http://localhost:3030/api/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@user.com",
  "password": "password"
}

###

GET http://localhost:3030/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGNjYTc4NDA5MmRhYWZlODFiNGJhNyIsImlhdCI6MTcyMTcwMzE1OSwiZXhwIjoxNzIxNzEwMzU5fQ.8PJTnEjFpM8KN-iFBYCbXOx-0wGotZ6xBLmbY-fxcMc